services:
    php:
        container_name: doghelp_php
        ports:
            - "8081:80"

    db:
        container_name: doghelp_db

networks:
    traefik_traefik_proxy:
        external: false
    doghelp_internal:
        driver: bridge
